# 1) Build
FROM node:20-alpine AS build
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .

# Variables de entorno en tiempo de build (inyectadas por EasyPanel)
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_SUPPORT_WHATSAPP
ARG VITE_ADMIN_WHATSAPP
ARG VITE_SUPPORT_EMAIL
ARG VITE_ADMIN_SUPPORT_EMAIL
ARG VITE_VAPID_EMAIL
ARG GEMINI_API_KEY

ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_SUPPORT_WHATSAPP=$VITE_SUPPORT_WHATSAPP
ENV VITE_ADMIN_WHATSAPP=$VITE_ADMIN_WHATSAPP
ENV VITE_SUPPORT_EMAIL=$VITE_SUPPORT_EMAIL
ENV VITE_ADMIN_SUPPORT_EMAIL=$VITE_ADMIN_SUPPORT_EMAIL
ENV VITE_VAPID_EMAIL=$VITE_VAPID_EMAIL
ENV GEMINI_API_KEY=$GEMINI_API_KEY

RUN npm run build

# 2) Serve static
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
